name: roopam
description: "portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_builder: ^0.7.1
  google_fonts: ^6.2.1
  provider: ^6.1.5
  delightful_toast: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  url_strategy: ^0.2.0
  logger: ^2.1.0
  entry: ^0.0.9
  animated_flip_counter: ^0.3.2
  visibility_detector: ^0.4.0+2
  auto_size_text: ^3.0.0
  go_router: ^14.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_mailer: ^2.1.2
  rive: ^0.13.20



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/

  fonts:
    - family: Fascinate
      fonts:
        - asset: assets/fonts/Fascinate-Regular.ttf
    - family: Eastbroadway
      fonts:
        - asset: assets/fonts/eastbroadway-semicondensedregular.otf
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-SemiBold.ttf

    - family: Goku
      fonts:
        - asset: assets/fonts/goku/Goku.ttf
        - asset: assets/fonts/goku/Goku Stencil.ttf
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
