name: roopam
description: "portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_builder: ^0.7.1
  google_fonts: ^6.2.1
  provider: ^6.1.5
  delightful_toast: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  url_strategy: ^0.2.0
  logger: ^2.1.0
  entry: ^0.0.9
  animated_flip_counter: ^0.3.2
  visibility_detector: ^0.4.0+2
  auto_size_text: ^3.0.0
  go_router: ^14.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_mailer: ^2.1.2
  rive: ^0.13.20
  animated_text_kit: ^4.2.3
  device_frame: ^1.4.0
  carousel_slider: ^5.1.1
  fading_edge_scrollview: ^4.1.1
  custom_button_builder: ^0.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: HokyaaSans
      fonts:
        - asset: assets/fonts/hokya-sans/Hokyaa Sans Reg.ttf
          weight: 400
        - asset: assets/fonts/hokya-sans/Hokyaa Sans Press.ttf
          weight: 700
    - family: ScotchDisplay
      fonts:
        - asset: assets/fonts/scotch_display/ScotchDisplay-Roman.ttf
        - asset: assets/fonts/scotch_display/ScotchDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/scotch_display/ScotchDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/scotch_display/ScotchDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/scotch_display/ScotchDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/scotch_display/ScotchDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/scotch_display/ScotchDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/scotch_display/ScotchDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/scotch_display/ScotchDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/scotch_display/ScotchDisplay-Fat.ttf
          weight: 900
        - asset: assets/fonts/scotch_display/ScotchDisplay-FatItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/scotch_display/ScotchDisplay-Italic.ttf
          style: italic

    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-SemiBold.ttf
